'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _deltaframe = _interopRequireDefault(require("deltaframe"));

var _button = _interopRequireDefault(require("./button/button"));

var _Mousebind = _interopRequireDefault(require("./button/Mousebind"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

/**
 * TODO
 */
var Mousehawk =
/*#__PURE__*/
function () {
  /**
   * A reference to the options for this instance of Mousehawk.
   * 
   * @property {Options}
   */

  /**
   * A list of mouse buttons that can be used to create mousebinds.
   * 
   * @property {MOUSE}
   * 
   * @private
   */

  /**
   * A list of the created mousebinds.
   * 
   * @property {Array<Mousebind>}
   * 
   * @private
   * 
   * @default []
   */

  /**
   * Keeps track of what mouse buttons have been pressed.
   * 
   * @property {Object}
   * 
   * @private
   */

  /**
   * Indicates whether using mousebinds are currently disabled or not.
   * 
   * @property {boolean}
   * 
   * @private
   * 
   * @default false
   */

  /**
   * The amount of time that mousebinds are disabled for if any.
   * 
   * @property {number}
   * 
   * @private
   * 
   * @default 0
   */

  /**
   * A reference to the Deltaframe game loop.
   * 
   * @property {Deltaframe}
   * 
   * @private
   */
  function Mousehawk() {
    _classCallCheck(this, Mousehawk);

    _defineProperty(this, "_options", void 0);

    _defineProperty(this, "_BUTTON", _button["default"]);

    _defineProperty(this, "_mousebinds", []);

    _defineProperty(this, "_pressed", {});

    _defineProperty(this, "_disabled", false);

    _defineProperty(this, "_disabledTime", 0);

    _defineProperty(this, "_loop", new _deltaframe["default"]());

    this._boot();
  }
  /**
   * Gets the mouse buttons that can be used to create mousebinds.
   * 
   * @returns {*}
   */


  _createClass(Mousehawk, [{
    key: "_boot",

    /**
     * Setup the mousedown and mouseup event listeners and also initialize Deltaframe if its being used.
     * 
     * @private
     */
    value: function _boot() {
      var _this = this;

      window.addEventListener('mousedown', function (ev) {
        return _this._onmousedown(ev);
      });
      window.addEventListener('mouseup', function (ev) {
        return _this._onmouseup(ev);
      });

      this._loop.start(function (time) {
        return _this.check(time);
      });
    }
    /**
     * When a mouse button is pressed, add it to the `pressed` object if it doesn't already exist and set it to `true`.
     * 
     * @private
     * 
     * @param {MouseEvent} ev The MouseEvent generated by the mouse button press.
     */

  }, {
    key: "_onmousedown",
    value: function _onmousedown(ev) {
      this._pressed[ev.buttons] = true;
      ev.preventDefault();
    }
    /**
     * When a mouse button is released, set its property in the `pressed` object to `false`.
     * 
     * @private
     * 
     * @param {MouseEvent} ev The MouseEvent generated by the mouse button press.
     */

  }, {
    key: "_onmouseup",
    value: function _onmouseup(ev) {
      this._pressed[ev.buttons] = false;
      ev.preventDefault();
    }
    /**
     * Creates a new mousebind for the specified mouse button.
     * 
     * @param {MousebindObject} mouseButton One or more mouse buttons from the `BUTTONS` property to attach to this mousebind.
     * 
     * @returns {Mousebind} Returns the newly created mousebind.
     */

  }, {
    key: "mousebind",
    value: function mousebind(mouseButton) {
      if (!mouseButton) {
        console.warn('A mouse button must be provided to create a mousebind');
        return;
      }

      var mouseObj = {};
      var mousebind = new _Mousebind["default"](mouseButton);

      this._mousebinds.push(mousebind);

      return mousebind;
    }
    /**
     * Checks to see which mouse button conditions are currently being met and runs the mousebinds's attached callback method.
      * 
      * @param {number} time The current timestamp which is used to check for delays and is passed to the mousebinds's callback method.
     */

  }, {
    key: "check",
    value: function check(time) {
      var _this2 = this;

      this._mousebinds.map(function (bind) {
        var button = bind.button.toString();
        var isActive = _this2._pressed[button];
        var isPastInitialDelay = time > bind._initialDelay;
        var isTime = time - bind.lastUsed > bind._delay;

        if (_this2._disabled) {
          if (time < time + _this2._disabledTime) return;else _this2.enable();
        }

        if (isActive && isPastInitialDelay && isTime && bind.action) bind.run(time);
      });
    }
    /**
     * Disables the use of all mousebinds until enable is called or until the wait time has expired if it is provided.
     * 
     * @param {number} [lengthOfTime=Infinity] An optional amount of time to wait until mousebinds are automatically enabled again. 
     */

  }, {
    key: "disable",
    value: function disable() {
      var lengthOfTime = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : Infinity;
      this._disabled = true;
      this._disabledTime = lengthOfTime;
    }
    /**
     * If no end time is passed when calling the `disable` method, this method has to be called to enable the use of
     * mousebind again.
     */

  }, {
    key: "enable",
    value: function enable() {
      this._disabled = false;
      this._disabledTime = 0;
    }
  }, {
    key: "BUTTON",
    get: function get() {
      return this._BUTTON;
    }
  }]);

  return Mousehawk;
}();

exports["default"] = Mousehawk;
;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3NyYy9pbmRleC50cyJdLCJuYW1lcyI6WyJNb3VzZWhhd2siLCJidXR0b24iLCJEZWx0YWZyYW1lIiwiX2Jvb3QiLCJ3aW5kb3ciLCJhZGRFdmVudExpc3RlbmVyIiwiZXYiLCJfb25tb3VzZWRvd24iLCJfb25tb3VzZXVwIiwiX2xvb3AiLCJzdGFydCIsInRpbWUiLCJjaGVjayIsIl9wcmVzc2VkIiwiYnV0dG9ucyIsInByZXZlbnREZWZhdWx0IiwibW91c2VCdXR0b24iLCJjb25zb2xlIiwid2FybiIsIm1vdXNlT2JqIiwibW91c2ViaW5kIiwiTW91c2ViaW5kIiwiX21vdXNlYmluZHMiLCJwdXNoIiwibWFwIiwiYmluZCIsInRvU3RyaW5nIiwiaXNBY3RpdmUiLCJpc1Bhc3RJbml0aWFsRGVsYXkiLCJfaW5pdGlhbERlbGF5IiwiaXNUaW1lIiwibGFzdFVzZWQiLCJfZGVsYXkiLCJfZGlzYWJsZWQiLCJfZGlzYWJsZWRUaW1lIiwiZW5hYmxlIiwiYWN0aW9uIiwicnVuIiwibGVuZ3RoT2ZUaW1lIiwiSW5maW5pdHkiLCJfQlVUVE9OIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7OztBQUVBOztBQUNBOztBQUNBOzs7Ozs7Ozs7Ozs7QUFHQTs7O0lBR3FCQSxTOzs7QUFFbkI7Ozs7OztBQU9BOzs7Ozs7OztBQVNBOzs7Ozs7Ozs7O0FBV0E7Ozs7Ozs7O0FBU0E7Ozs7Ozs7Ozs7QUFXQTs7Ozs7Ozs7OztBQVdBOzs7Ozs7O0FBU0EsdUJBQWM7QUFBQTs7QUFBQTs7QUFBQSxxQ0FyRFNDLGtCQXFEVDs7QUFBQSx5Q0ExQzBCLEVBMEMxQjs7QUFBQSxzQ0FqQ1UsRUFpQ1Y7O0FBQUEsdUNBdEJlLEtBc0JmOztBQUFBLDJDQVhrQixDQVdsQjs7QUFBQSxtQ0FGYyxJQUFJQyxzQkFBSixFQUVkOztBQUVaLFNBQUtDLEtBQUw7QUFFRDtBQUVEOzs7Ozs7Ozs7O0FBV0E7Ozs7OzRCQUtnQjtBQUFBOztBQUVkQyxNQUFBQSxNQUFNLENBQUNDLGdCQUFQLENBQXdCLFdBQXhCLEVBQXFDLFVBQUNDLEVBQUQ7QUFBQSxlQUFvQixLQUFJLENBQUNDLFlBQUwsQ0FBa0JELEVBQWxCLENBQXBCO0FBQUEsT0FBckM7QUFFQUYsTUFBQUEsTUFBTSxDQUFDQyxnQkFBUCxDQUF3QixTQUF4QixFQUFtQyxVQUFDQyxFQUFEO0FBQUEsZUFBb0IsS0FBSSxDQUFDRSxVQUFMLENBQWdCRixFQUFoQixDQUFwQjtBQUFBLE9BQW5DOztBQUVBLFdBQUtHLEtBQUwsQ0FBV0MsS0FBWCxDQUFpQixVQUFDQyxJQUFEO0FBQUEsZUFBa0IsS0FBSSxDQUFDQyxLQUFMLENBQVdELElBQVgsQ0FBbEI7QUFBQSxPQUFqQjtBQUVEO0FBRUQ7Ozs7Ozs7Ozs7aUNBT3FCTCxFLEVBQWdCO0FBRW5DLFdBQUtPLFFBQUwsQ0FBY1AsRUFBRSxDQUFDUSxPQUFqQixJQUE0QixJQUE1QjtBQUVBUixNQUFBQSxFQUFFLENBQUNTLGNBQUg7QUFFRDtBQUVEOzs7Ozs7Ozs7OytCQU9tQlQsRSxFQUFnQjtBQUVqQyxXQUFLTyxRQUFMLENBQWNQLEVBQUUsQ0FBQ1EsT0FBakIsSUFBNEIsS0FBNUI7QUFFQVIsTUFBQUEsRUFBRSxDQUFDUyxjQUFIO0FBRUQ7QUFFRDs7Ozs7Ozs7Ozs4QkFPVUMsVyxFQUE4QjtBQUV0QyxVQUFJLENBQUNBLFdBQUwsRUFBa0I7QUFFaEJDLFFBQUFBLE9BQU8sQ0FBQ0MsSUFBUixDQUFhLHVEQUFiO0FBRUE7QUFFRDs7QUFFRCxVQUFNQyxRQUF5QixHQUFHLEVBQWxDO0FBRUEsVUFBTUMsU0FBb0IsR0FBRyxJQUFJQyxxQkFBSixDQUFjTCxXQUFkLENBQTdCOztBQUVBLFdBQUtNLFdBQUwsQ0FBaUJDLElBQWpCLENBQXNCSCxTQUF0Qjs7QUFFQSxhQUFPQSxTQUFQO0FBRUQ7QUFFRjs7Ozs7Ozs7MEJBS09ULEksRUFBYztBQUFBOztBQUVsQixXQUFLVyxXQUFMLENBQWlCRSxHQUFqQixDQUFxQixVQUFBQyxJQUFJLEVBQUk7QUFFM0IsWUFBTXhCLE1BQWMsR0FBR3dCLElBQUksQ0FBQ3hCLE1BQUwsQ0FBWXlCLFFBQVosRUFBdkI7QUFFQSxZQUFNQyxRQUFpQixHQUFHLE1BQUksQ0FBQ2QsUUFBTCxDQUFjWixNQUFkLENBQTFCO0FBRUEsWUFBTTJCLGtCQUEyQixHQUFHakIsSUFBSSxHQUFHYyxJQUFJLENBQUNJLGFBQWhEO0FBRUEsWUFBTUMsTUFBZSxHQUFHbkIsSUFBSSxHQUFHYyxJQUFJLENBQUNNLFFBQVosR0FBdUJOLElBQUksQ0FBQ08sTUFBcEQ7O0FBRUEsWUFBSSxNQUFJLENBQUNDLFNBQVQsRUFBb0I7QUFFbEIsY0FBSXRCLElBQUksR0FBR0EsSUFBSSxHQUFHLE1BQUksQ0FBQ3VCLGFBQXZCLEVBQXNDLE9BQXRDLEtBRUssTUFBSSxDQUFDQyxNQUFMO0FBRU47O0FBRUQsWUFBSVIsUUFBUSxJQUFJQyxrQkFBWixJQUFrQ0UsTUFBbEMsSUFBNENMLElBQUksQ0FBQ1csTUFBckQsRUFBNkRYLElBQUksQ0FBQ1ksR0FBTCxDQUFTMUIsSUFBVDtBQUU5RCxPQXBCRDtBQXNCRDtBQUVEOzs7Ozs7Ozs4QkFLeUM7QUFBQSxVQUFqQzJCLFlBQWlDLHVFQUFWQyxRQUFVO0FBRXZDLFdBQUtOLFNBQUwsR0FBaUIsSUFBakI7QUFFQSxXQUFLQyxhQUFMLEdBQXFCSSxZQUFyQjtBQUVEO0FBRUQ7Ozs7Ozs7NkJBSVM7QUFFUCxXQUFLTCxTQUFMLEdBQWlCLEtBQWpCO0FBRUEsV0FBS0MsYUFBTCxHQUFxQixDQUFyQjtBQUdEOzs7d0JBcklpQjtBQUVoQixhQUFPLEtBQUtNLE9BQVo7QUFFRDs7Ozs7OztBQW1JRiIsInNvdXJjZXNDb250ZW50IjpbIid1c2Ugc3RyaWN0J1xyXG5cclxuaW1wb3J0IERlbHRhZnJhbWUgZnJvbSAnZGVsdGFmcmFtZSc7XHJcbmltcG9ydCBidXR0b24gZnJvbSAnLi9idXR0b24vYnV0dG9uJztcclxuaW1wb3J0IE1vdXNlYmluZCBmcm9tICcuL2J1dHRvbi9Nb3VzZWJpbmQnO1xyXG5pbXBvcnQgTW91c2ViaW5kT2JqZWN0IGZyb20gJy4vaW50ZXJmYWNlcy9Nb3VzZWJpbmRPYmplY3QnO1xyXG5cclxuLyoqXHJcbiAqIFRPRE9cclxuICovXHJcbmV4cG9ydCBkZWZhdWx0IGNsYXNzIE1vdXNlaGF3ayB7XHJcblxyXG4gIC8qKlxyXG4gICAqIEEgcmVmZXJlbmNlIHRvIHRoZSBvcHRpb25zIGZvciB0aGlzIGluc3RhbmNlIG9mIE1vdXNlaGF3ay5cclxuICAgKiBcclxuICAgKiBAcHJvcGVydHkge09wdGlvbnN9XHJcbiAgICovXHJcbiAgcHJpdmF0ZSBfb3B0aW9uczogYW55O1xyXG5cclxuICAvKipcclxuICAgKiBBIGxpc3Qgb2YgbW91c2UgYnV0dG9ucyB0aGF0IGNhbiBiZSB1c2VkIHRvIGNyZWF0ZSBtb3VzZWJpbmRzLlxyXG4gICAqIFxyXG4gICAqIEBwcm9wZXJ0eSB7TU9VU0V9XHJcbiAgICogXHJcbiAgICogQHByaXZhdGVcclxuICAgKi9cclxuICBwcml2YXRlIF9CVVRUT046IGFueSA9IGJ1dHRvbjtcclxuXHJcbiAgLyoqXHJcbiAgICogQSBsaXN0IG9mIHRoZSBjcmVhdGVkIG1vdXNlYmluZHMuXHJcbiAgICogXHJcbiAgICogQHByb3BlcnR5IHtBcnJheTxNb3VzZWJpbmQ+fVxyXG4gICAqIFxyXG4gICAqIEBwcml2YXRlXHJcbiAgICogXHJcbiAgICogQGRlZmF1bHQgW11cclxuICAgKi9cclxuICBwcml2YXRlIF9tb3VzZWJpbmRzOiBBcnJheTxNb3VzZWJpbmQ+ID0gW107XHJcblxyXG4gIC8qKlxyXG4gICAqIEtlZXBzIHRyYWNrIG9mIHdoYXQgbW91c2UgYnV0dG9ucyBoYXZlIGJlZW4gcHJlc3NlZC5cclxuICAgKiBcclxuICAgKiBAcHJvcGVydHkge09iamVjdH1cclxuICAgKiBcclxuICAgKiBAcHJpdmF0ZVxyXG4gICAqL1xyXG4gIHByaXZhdGUgX3ByZXNzZWQ6IGFueSA9IHt9O1xyXG5cclxuICAvKipcclxuICAgKiBJbmRpY2F0ZXMgd2hldGhlciB1c2luZyBtb3VzZWJpbmRzIGFyZSBjdXJyZW50bHkgZGlzYWJsZWQgb3Igbm90LlxyXG4gICAqIFxyXG4gICAqIEBwcm9wZXJ0eSB7Ym9vbGVhbn1cclxuICAgKiBcclxuICAgKiBAcHJpdmF0ZVxyXG4gICAqIFxyXG4gICAqIEBkZWZhdWx0IGZhbHNlXHJcbiAgICovXHJcbiAgcHJpdmF0ZSBfZGlzYWJsZWQ6IGJvb2xlYW4gPSBmYWxzZTtcclxuXHJcbiAgLyoqXHJcbiAgICogVGhlIGFtb3VudCBvZiB0aW1lIHRoYXQgbW91c2ViaW5kcyBhcmUgZGlzYWJsZWQgZm9yIGlmIGFueS5cclxuICAgKiBcclxuICAgKiBAcHJvcGVydHkge251bWJlcn1cclxuICAgKiBcclxuICAgKiBAcHJpdmF0ZVxyXG4gICAqIFxyXG4gICAqIEBkZWZhdWx0IDBcclxuICAgKi9cclxuICBwcml2YXRlIF9kaXNhYmxlZFRpbWU6IG51bWJlciA9IDA7XHJcblxyXG4gIC8qKlxyXG4gICAqIEEgcmVmZXJlbmNlIHRvIHRoZSBEZWx0YWZyYW1lIGdhbWUgbG9vcC5cclxuICAgKiBcclxuICAgKiBAcHJvcGVydHkge0RlbHRhZnJhbWV9XHJcbiAgICogXHJcbiAgICogQHByaXZhdGVcclxuICAgKi9cclxuICBwcml2YXRlIF9sb29wOiBEZWx0YWZyYW1lID0gbmV3IERlbHRhZnJhbWUoKTtcclxuXHJcbiAgY29uc3RydWN0b3IoKSB7XHJcblxyXG4gICAgdGhpcy5fYm9vdCgpO1xyXG5cclxuICB9XHJcblxyXG4gIC8qKlxyXG4gICAqIEdldHMgdGhlIG1vdXNlIGJ1dHRvbnMgdGhhdCBjYW4gYmUgdXNlZCB0byBjcmVhdGUgbW91c2ViaW5kcy5cclxuICAgKiBcclxuICAgKiBAcmV0dXJucyB7Kn1cclxuICAgKi9cclxuICBnZXQgQlVUVE9OKCk6IGFueSB7XHJcblxyXG4gICAgcmV0dXJuIHRoaXMuX0JVVFRPTjtcclxuXHJcbiAgfVxyXG5cclxuICAvKipcclxuICAgKiBTZXR1cCB0aGUgbW91c2Vkb3duIGFuZCBtb3VzZXVwIGV2ZW50IGxpc3RlbmVycyBhbmQgYWxzbyBpbml0aWFsaXplIERlbHRhZnJhbWUgaWYgaXRzIGJlaW5nIHVzZWQuXHJcbiAgICogXHJcbiAgICogQHByaXZhdGVcclxuICAgKi9cclxuICBwcml2YXRlIF9ib290KCkge1xyXG5cclxuICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtb3VzZWRvd24nLCAoZXY6IE1vdXNlRXZlbnQpID0+IHRoaXMuX29ubW91c2Vkb3duKGV2KSk7XHJcblxyXG4gICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21vdXNldXAnLCAoZXY6IE1vdXNlRXZlbnQpID0+IHRoaXMuX29ubW91c2V1cChldikpO1xyXG5cclxuICAgIHRoaXMuX2xvb3Auc3RhcnQoKHRpbWU6IG51bWJlcikgPT4gdGhpcy5jaGVjayh0aW1lKSk7XHJcblxyXG4gIH1cclxuXHJcbiAgLyoqXHJcbiAgICogV2hlbiBhIG1vdXNlIGJ1dHRvbiBpcyBwcmVzc2VkLCBhZGQgaXQgdG8gdGhlIGBwcmVzc2VkYCBvYmplY3QgaWYgaXQgZG9lc24ndCBhbHJlYWR5IGV4aXN0IGFuZCBzZXQgaXQgdG8gYHRydWVgLlxyXG4gICAqIFxyXG4gICAqIEBwcml2YXRlXHJcbiAgICogXHJcbiAgICogQHBhcmFtIHtNb3VzZUV2ZW50fSBldiBUaGUgTW91c2VFdmVudCBnZW5lcmF0ZWQgYnkgdGhlIG1vdXNlIGJ1dHRvbiBwcmVzcy5cclxuICAgKi9cclxuICBwcml2YXRlIF9vbm1vdXNlZG93bihldjogTW91c2VFdmVudCkge1xyXG5cclxuICAgIHRoaXMuX3ByZXNzZWRbZXYuYnV0dG9uc10gPSB0cnVlO1xyXG5cclxuICAgIGV2LnByZXZlbnREZWZhdWx0KCk7XHJcblxyXG4gIH1cclxuXHJcbiAgLyoqXHJcbiAgICogV2hlbiBhIG1vdXNlIGJ1dHRvbiBpcyByZWxlYXNlZCwgc2V0IGl0cyBwcm9wZXJ0eSBpbiB0aGUgYHByZXNzZWRgIG9iamVjdCB0byBgZmFsc2VgLlxyXG4gICAqIFxyXG4gICAqIEBwcml2YXRlXHJcbiAgICogXHJcbiAgICogQHBhcmFtIHtNb3VzZUV2ZW50fSBldiBUaGUgTW91c2VFdmVudCBnZW5lcmF0ZWQgYnkgdGhlIG1vdXNlIGJ1dHRvbiBwcmVzcy5cclxuICAgKi9cclxuICBwcml2YXRlIF9vbm1vdXNldXAoZXY6IE1vdXNlRXZlbnQpIHtcclxuXHJcbiAgICB0aGlzLl9wcmVzc2VkW2V2LmJ1dHRvbnNdID0gZmFsc2U7XHJcblxyXG4gICAgZXYucHJldmVudERlZmF1bHQoKTtcclxuXHJcbiAgfVxyXG5cclxuICAvKipcclxuICAgKiBDcmVhdGVzIGEgbmV3IG1vdXNlYmluZCBmb3IgdGhlIHNwZWNpZmllZCBtb3VzZSBidXR0b24uXHJcbiAgICogXHJcbiAgICogQHBhcmFtIHtNb3VzZWJpbmRPYmplY3R9IG1vdXNlQnV0dG9uIE9uZSBvciBtb3JlIG1vdXNlIGJ1dHRvbnMgZnJvbSB0aGUgYEJVVFRPTlNgIHByb3BlcnR5IHRvIGF0dGFjaCB0byB0aGlzIG1vdXNlYmluZC5cclxuICAgKiBcclxuICAgKiBAcmV0dXJucyB7TW91c2ViaW5kfSBSZXR1cm5zIHRoZSBuZXdseSBjcmVhdGVkIG1vdXNlYmluZC5cclxuICAgKi9cclxuICBtb3VzZWJpbmQobW91c2VCdXR0b246IE1vdXNlYmluZE9iamVjdCkge1xyXG5cclxuICAgIGlmICghbW91c2VCdXR0b24pIHtcclxuXHJcbiAgICAgIGNvbnNvbGUud2FybignQSBtb3VzZSBidXR0b24gbXVzdCBiZSBwcm92aWRlZCB0byBjcmVhdGUgYSBtb3VzZWJpbmQnKTtcclxuXHJcbiAgICAgIHJldHVybjtcclxuXHJcbiAgICB9XHJcblxyXG4gICAgY29uc3QgbW91c2VPYmo6IE1vdXNlYmluZE9iamVjdCA9IHt9O1xyXG5cclxuICAgIGNvbnN0IG1vdXNlYmluZDogTW91c2ViaW5kID0gbmV3IE1vdXNlYmluZChtb3VzZUJ1dHRvbik7XHJcblxyXG4gICAgdGhpcy5fbW91c2ViaW5kcy5wdXNoKG1vdXNlYmluZCk7XHJcblxyXG4gICAgcmV0dXJuIG1vdXNlYmluZDtcclxuXHJcbiAgfVxyXG5cclxuXHQvKipcclxuXHQgKiBDaGVja3MgdG8gc2VlIHdoaWNoIG1vdXNlIGJ1dHRvbiBjb25kaXRpb25zIGFyZSBjdXJyZW50bHkgYmVpbmcgbWV0IGFuZCBydW5zIHRoZSBtb3VzZWJpbmRzJ3MgYXR0YWNoZWQgY2FsbGJhY2sgbWV0aG9kLlxyXG4gICAqIFxyXG4gICAqIEBwYXJhbSB7bnVtYmVyfSB0aW1lIFRoZSBjdXJyZW50IHRpbWVzdGFtcCB3aGljaCBpcyB1c2VkIHRvIGNoZWNrIGZvciBkZWxheXMgYW5kIGlzIHBhc3NlZCB0byB0aGUgbW91c2ViaW5kcydzIGNhbGxiYWNrIG1ldGhvZC5cclxuXHQgKi9cclxuICBjaGVjayh0aW1lOiBudW1iZXIpIHtcclxuXHJcbiAgICB0aGlzLl9tb3VzZWJpbmRzLm1hcChiaW5kID0+IHtcclxuXHJcbiAgICAgIGNvbnN0IGJ1dHRvbjogc3RyaW5nID0gYmluZC5idXR0b24udG9TdHJpbmcoKTtcclxuXHJcbiAgICAgIGNvbnN0IGlzQWN0aXZlOiBib29sZWFuID0gdGhpcy5fcHJlc3NlZFtidXR0b25dO1xyXG5cclxuICAgICAgY29uc3QgaXNQYXN0SW5pdGlhbERlbGF5OiBib29sZWFuID0gdGltZSA+IGJpbmQuX2luaXRpYWxEZWxheTtcclxuXHJcbiAgICAgIGNvbnN0IGlzVGltZTogYm9vbGVhbiA9IHRpbWUgLSBiaW5kLmxhc3RVc2VkID4gYmluZC5fZGVsYXk7XHJcblxyXG4gICAgICBpZiAodGhpcy5fZGlzYWJsZWQpIHtcclxuXHJcbiAgICAgICAgaWYgKHRpbWUgPCB0aW1lICsgdGhpcy5fZGlzYWJsZWRUaW1lKSByZXR1cm47XHJcblxyXG4gICAgICAgIGVsc2UgdGhpcy5lbmFibGUoKTtcclxuXHJcbiAgICAgIH1cclxuXHJcbiAgICAgIGlmIChpc0FjdGl2ZSAmJiBpc1Bhc3RJbml0aWFsRGVsYXkgJiYgaXNUaW1lICYmIGJpbmQuYWN0aW9uKSBiaW5kLnJ1bih0aW1lKTtcclxuXHJcbiAgICB9KTtcclxuXHJcbiAgfVxyXG5cclxuICAvKipcclxuICAgKiBEaXNhYmxlcyB0aGUgdXNlIG9mIGFsbCBtb3VzZWJpbmRzIHVudGlsIGVuYWJsZSBpcyBjYWxsZWQgb3IgdW50aWwgdGhlIHdhaXQgdGltZSBoYXMgZXhwaXJlZCBpZiBpdCBpcyBwcm92aWRlZC5cclxuICAgKiBcclxuICAgKiBAcGFyYW0ge251bWJlcn0gW2xlbmd0aE9mVGltZT1JbmZpbml0eV0gQW4gb3B0aW9uYWwgYW1vdW50IG9mIHRpbWUgdG8gd2FpdCB1bnRpbCBtb3VzZWJpbmRzIGFyZSBhdXRvbWF0aWNhbGx5IGVuYWJsZWQgYWdhaW4uIFxyXG4gICAqL1xyXG4gIGRpc2FibGUobGVuZ3RoT2ZUaW1lOiBudW1iZXIgPSBJbmZpbml0eSkge1xyXG5cclxuICAgIHRoaXMuX2Rpc2FibGVkID0gdHJ1ZTtcclxuXHJcbiAgICB0aGlzLl9kaXNhYmxlZFRpbWUgPSBsZW5ndGhPZlRpbWU7XHJcblxyXG4gIH1cclxuXHJcbiAgLyoqXHJcbiAgICogSWYgbm8gZW5kIHRpbWUgaXMgcGFzc2VkIHdoZW4gY2FsbGluZyB0aGUgYGRpc2FibGVgIG1ldGhvZCwgdGhpcyBtZXRob2QgaGFzIHRvIGJlIGNhbGxlZCB0byBlbmFibGUgdGhlIHVzZSBvZlxyXG4gICAqIG1vdXNlYmluZCBhZ2Fpbi5cclxuICAgKi9cclxuICBlbmFibGUoKSB7XHJcblxyXG4gICAgdGhpcy5fZGlzYWJsZWQgPSBmYWxzZVxyXG5cclxuICAgIHRoaXMuX2Rpc2FibGVkVGltZSA9IDA7XHJcblxyXG5cclxuICB9XHJcblxyXG59OyJdfQ==